### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by rj-d2** [BreadedChickenator/Cross-Seed-AutoDL#1]
hi,

im curious if you could make this work, for ubuntu / linux,
i would love to have this running directly on my seedbox!!!!!!
keep up the great work!

**Comment by ans1genie** [comment]
I am wondering it could be dynamically fixed for any other platforms.
Windows/Linux/MacOS

**Comment by BC44** [comment]
I've adjusted the script to work on Linux/MacOS in f5f481e9a50e2258d9445e10a1f2700b863c0568. Give it a whirl!
