### ISSUE TITLE
Getting error when searching

### ISSUE THREAD

**Issue by R3D4CTED** [BreadedChickenator/Cross-Seed-AutoDL#11]
Error:
```
Traceback (most recent call last):
  File "CrossSeedAutoDL.py", line 354, in <module>
    main()
  File "CrossSeedAutoDL.py", line 313, in main
    title=local_release_data['guessed_data']['title'],
KeyError: 'title'
```

**Comment by R3D4CTED** [comment]
Added a `try: except:` block around the `info` variable definition and made it `continue`,  however, that is just temporarily suppressing the issue to make script usable and not break the others.

**Comment by BC44** [comment]
Interesting, what is the filename that this is happening for?

**Comment by BC44** [comment]
Well, I added a skip for when the title can't be guessed. If further issues arise, create a new issue, please.
