### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by babos123** [BreadedChickenator/Cross-Seed-AutoDL#16]
I have change the categories so jackett can search ebooks.
Working fine.
Today i saw this error.

Searching for 716 of 9787: Shrubs
5 matched of 43 results.
- Grabbing release: Shrubs An Old-Fashioned Drink for Modern Times (2nd Edition) by Michael Dietsch [2016] [EPUB] [Retail] [B]
- Grabbing release: 50 Beautiful Deer-Resistant Plants The Prettiest Annuals Perennials Bulbs and Shrubs That Deer Dont Eat by Ruth Rogers Clausen [2011] [PDF] [Retail] [B]
- Grabbing release: Mocktails Punches and Shrubs Over 80 Nonalcoholic Drinks to Savor and Enjoy by Vikas Khanna [2017] [PDF] [Retail] [B]
- Grabbing release: The Art of Creative Pruning Inventive Ideas for Training and Shaping Trees and Shrubs by Jake Hobson [2012] [EPUB] [Retail] [B]
- Grabbing release: Homemade Soda 200 Recipes for Making  Using Fruit Sodas  Fizzy Juices Sparkling Waters Root Beers  Cola Brews Herbal  Healing Waters Sparkling Teas  Coffees Shrubs  Switchels Cream Sodas  Floats  Other Carbonated Concoctions by Andrew Schloss [2011] [PDF] [Retail] [B]
Traceback (most recent call last):
  File "CrossSeedAutoDL.py", line 399, in <module>
    main()
  File "CrossSeedAutoDL.py", line 374, in main
    Downloader.download(result, search_history)
  File "CrossSeedAutoDL.py", line 272, in download
    with open(file_path, 'wb') as f:
OSError: [Errno 36] File name too long: '/mnt/downloads2/incomplete/rutorrent/2/Homemade Soda 200 Recipes for Making  Using Fruit Sodas  Fizzy Juices Sparkling Waters Root Beers  Cola Brews Herbal  Healing Waters Sparkling Teas  Coffees Shrubs  Switchels Cream Sodas  Floats  Other Carbonated Concoctions by Andrew Schloss [2011] [PDF] [Retail] [B].torrent'

**Comment by babos123** [comment]
Just saw latest fix. Using it right now and seems that working.
closing

**Comment by babos123** [comment]
Still not working

Traceback (most recent call last):
  File "CrossSeedAutoDL.py", line 410, in <module>
    main()
  File "CrossSeedAutoDL.py", line 373, in main
    Downloader.download(result, search_history)
  File "CrossSeedAutoDL.py", line 272, in download
    with open(file_path, 'wb') as f:
OSError: [Errno 36] File name too long: '/mnt/downloads2/incomplete/rutorrent/2/The Backyard Homestead Book of Building Projects 76 Useful Things You Can Build to Create Customized Working Spaces and Storage Facilities Equip the Garden Store the Harvest House Your Animals and Make Practical Outdoor Furniture by Spike Carlsen [2013] [EPUB] [Retail] [B].torrent'

**Comment by BC44** [comment]
Fixed in b5cb242da53af630c8eabc802ec6007447e07f42

**Comment by babos123** [comment]
Testing right now.Thanks.
I will be back later to inform you

**Comment by babos123** [comment]
sorry for late respond
Searching for 4908 of 9779:
i think its enough.
closing
