### ISSUE TITLE
[Suggestion] Adding the tracker name at the torrent file name

### ISSUE THREAD

**Issue by hummingbirdy2** [BreadedChickenator/Cross-Seed-AutoDL#17]
It would be nice to add the tracker name at the torrent file name.
Something like `[TrackerName] Filename.torrent`

In case of multi result, the result would be much better:
```
- [Tracker A] My.Wonderful.Movie.torrent
- [Tracker B] My.Wonderful.Movie.torrent
- [Tracker C] My.Wonderful.Movie.torrent
```
Intead of:
```
- My.Wonderful.Movie.torrent
- My.Wonderful.Movie (1).torrent
- My.Wonderful.Movie (2).torrent
```
The name of the torrent is use as the base by `autotorrent` to create the directory for links.
I did some test with my fork, it's work very well with `autotorrent`. Much easiest to manage and far cleaner.

I can propose a PR if you are interested.

**Comment by BC44** [comment]
It was already doing this, but the tracker name was included at the end of the file, which would be truncated if the file name was too long. I've moved it to the start of the file name in e2da87ca10a14737edfda211c3ce5c9d332b2410

**Comment by hummingbirdy2** [comment]
Nice. I miss it. Sorry for the disturbance.

Thanks for your quick answer.
