### ISSUE TITLE
`SearchHistory.json` is not created if missing

### ISSUE THREAD

**Issue by hummingbirdy2** [BreadedChickenator/Cross-Seed-AutoDL#18]
I have this traceback with the `--ignore-history` used :
```python
Traceback (most recent call last):
  File "/app/cross-seed/CrossSeedAutoDL.py", line 429, in <module>
    main()
  File "/app/cross-seed/CrossSeedAutoDL.py", line 357, in main
    history_json_fd = open(HistoryManager.search_history_file_path, 'r+', encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: '/app/cross-seed/SearchHistory.json'
```
Is it really necessary to try to read (or check) the history file in this case ?

**Comment by hummingbirdy2** [comment]
My bad I mixed up with DownloadHistory.json

**Comment by BC44** [comment]
Yes, it needs to write new downloads to it. I've fixed it in 5aad05938ef22eda985d0a0e85102b9ccb0082f1

Btw `DownloadHistory.json` is old and no longer used. It's a relic of an older version of the script

**Comment by hummingbirdy2** [comment]
Thanks for the hot fix.

I don't understand the option `--ignore-history` if it steal need to write the new dl.

Seems not available for the moment. Is it possible to have the possibility to chose the path of the `SearchHistory.json` by a option ? To have an easiest gestion of the history with docker.

**Comment by BC44** [comment]
`--ignore-history` is there to allow torrents to be searched and downloaded even if they've already been searched/downloaded. It will still need to log the results for future iterations

**Comment by hummingbirdy2** [comment]
Thanks for the clarification
